/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Doubt = IDL.Record({
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'attachment' : IDL.Opt(ExternalBlob),
});
export const Answer = IDL.Record({
  'responder' : IDL.Principal,
  'video' : IDL.Opt(ExternalBlob),
  'doubtId' : IDL.Principal,
  'text' : IDL.Text,
  'numRatings' : IDL.Nat,
  'notes' : IDL.Opt(ExternalBlob),
  'rating' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'Junior' : IDL.Null,
  'Senior' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const LeaderboardEntry = IDL.Record({
  'userId' : IDL.Principal,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getAllDoubts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Doubt))],
      ['query'],
    ),
  'getAnswersForDoubt' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Answer))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postAnswer' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'postDoubt' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'rateAnswer' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Doubt = IDL.Record({
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'attachment' : IDL.Opt(ExternalBlob),
  });
  const Answer = IDL.Record({
    'responder' : IDL.Principal,
    'video' : IDL.Opt(ExternalBlob),
    'doubtId' : IDL.Principal,
    'text' : IDL.Text,
    'numRatings' : IDL.Nat,
    'notes' : IDL.Opt(ExternalBlob),
    'rating' : IDL.Float64,
  });
  const UserRole = IDL.Variant({ 'Junior' : IDL.Null, 'Senior' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const LeaderboardEntry = IDL.Record({
    'userId' : IDL.Principal,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getAllDoubts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Doubt))],
        ['query'],
      ),
    'getAnswersForDoubt' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Answer))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postAnswer' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'postDoubt' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'rateAnswer' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };